CREATE DATABASE NFCM
GO

USE NFCM
GO

SET DATEFORMAT DMY
GO

------------------------------------------
CREATE TABLE PhanMem
(
	A INT,
	B INT,
	C INT,
	Language INT,
	X INT,
	Y INT,
	Z INT
)
GO


CREATE TABLE MuaGiai
(
	IDMG INT IDENTITY(1,1) PRIMARY KEY,
	TenMG NVARCHAR(50),
	Nam INT,
)
GO

ALTER TABLE MuaGiai
ADD MuaGiaiHienTai BIT
GO

CREATE TABLE QuyDinh
(
	IDMG INT,
	SLDB INT,
	SLVD INT,
	TuoiTT INT,
	TuoiTD INT
)
GO

ALTER TABLE QuyDinh
ADD SLTT INT
GO

ALTER TABLE QuyDinh
ADD SLTD INT
GO

ALTER TABLE QuyDinh
ADD CONSTRAINT DF_QD_SLTT DEFAULT(15) FOR SLTT
GO

ALTER TABLE QuyDinh
ADD CONSTRAINT DF_QD_SLTD DEFAULT(25) FOR SLTD
GO

ALTER TABLE QuyDinh
ADD CONSTRAINT DF_QD_TuoiTT DEFAULT(16) FOR TuoiTT
GO

ALTER TABLE QuyDinh
ADD CONSTRAINT DF_QD_TuoiTD DEFAULT(40) FOR TuoiTD
GO

CREATE TABLE LoaiCauThu
(
	IDLCT INT IDENTITY(1,1) PRIMARY KEY,
	TenLCT NVARCHAR(50),
	IDMG INT,
	SLTD INT,

	CONSTRAINT FK_LCT_IDMG FOREIGN KEY (IDMG) REFERENCES MuaGiai(IDMG)
)
GO

CREATE TABLE CauThu
(
	IDCT INT IDENTITY(1,1) PRIMARY KEY,
	IDLCT INT,
	Ten NVARCHAR(50),
	GioiTinh NVARCHAR(30),
	QuocTich NVARCHAR(50),
	NgaySinh SMALLDATETIME,
	GhiChu NVARCHAR(1000),

	CONSTRAINT FK_CT_IDLCT FOREIGN KEY (IDLCT) REFERENCES LoaiCauThu(IDLCT)
)
GO

ALTER TABLE CauThu
ADD IDDB INT
GO

ALTER TABLE CAUTHU
ADD TONGBANTHANG INT DEFAULT 0
GO

ALTER TABLE CauThu
ADD HinhAnh IMAGE
GO


CREATE TABLE DoiBong
(
	IDDB INT IDENTITY(1,1) PRIMARY KEY,
	TenDB NVARCHAR(50)
)
GO

AlTER TABLE DoiBong
ADD TenHLV NVARCHAR(50)
GO

ALTER TABLE DoiBong
ADD SanNha NVARCHAR(50)
GO

ALTER TABLE DoiBong
ADD IDMG INT
GO

ALTER TABLE DoiBong
ADD HinhAnh IMAGE
GO

ALTER TABLE CauThu 
ADD CONSTRAINT FK_CT_IDDB FOREIGN KEY(IDDB) REFERENCES DoiBong(IDDB)
GO

CREATE TABLE TranDau
(
	IDMG INT,
	IDTranDau INT IDENTITY(1,1) PRIMARY KEY,
	VongDau INT,
	Doi1 INT,
	Doi2 INT,
	ThoiGian SMALLDATETIME DEFAULT GETDATE(),
	SanVanDong NVARCHAR(50),

	CONSTRAINT FK_LTD_IDMG FOREIGN KEY (IDMG) REFERENCES MuaGiai(IDMG),
	CONSTRAINT FK_LTD_Doi1 FOREIGN KEY (Doi1) REFERENCES DoiBong(IDDB),
	CONSTRAINT FK_LTD_Doi2 FOREIGN KEY (Doi2) REFERENCES DoiBong(IDDB)
)
GO

CREATE TABLE KetQuaThiDau
(
	IDTranDau INT,
	KQDoi1 INT,
	KQDoi2 INT,
	LuanLuu BIT,
	KQLL1 INT,
	KQLL2 INT,

	CONSTRAINT FK_KQTD_IDTranDau FOREIGN KEY (IDTranDau) REFERENCES TranDau(IDTranDau)
)
GO
ALTER TABLE KETQUATHIDAU
ADD CONSTRAINT DF_KQDOI1
DEFAULT -1 FOR KQDOI1
ALTER TABLE KETQUATHIDAU
ADD CONSTRAINT DF_KQDOI2
DEFAULT -1 FOR KQDOI2

CREATE TABLE LoaiBanThang
(
	IDLBT INT IDENTITY(1,1) PRIMARY KEY,
	TenLBT NVARCHAR(50),
	IDMG INT
)
GO

CREATE TABLE BanThang
(
	IDTranDau INT,
	IDCT INT,
	IDDB INT,
	IDLBT INT,
	ThoiDiem VARCHAR(10),

	CONSTRAINT FK_GB_IDTranDau FOREIGN KEY (IDTranDau) REFERENCES TranDau(IDTranDau),
	CONSTRAINT FK_GB_IDCT FOREIGN KEY (IDCT) REFERENCES CauThu(IDCT),
	CONSTRAINT FK_GB_IDDB FOREIGN KEY (IDDB) REFERENCES DoiBong(IDDB),
	CONSTRAINT FK_GB_IDLBT FOREIGN KEY (IDLBT) REFERENCES LoaiBanThang(IDLBT)
)
GO

ALTER TABLE BanThang
ADD IDBT INT IDENTITY(1,1) PRIMARY KEY
GO

CREATE TABLE QuyDinhDiemSo
(
	THANG INT DEFAULT 3,
	HOA INT DEFAULT 1,
	THUA INT DEFAULT 0.
	IDMG INT
)
GO

CREATE TABLE QuyDinhXepHang
(
	IDXH INT IDENTITY(1,1) PRIMARY KEY,
	Ten NVARCHAR(100),
	ThuTuUuTien INT,
	IDMG INT
)
GO

 -- INSERT DATA TO DEBUG
INSERT INTO MuaGiai(TenMG, Nam, MuaGiaiHienTai)
VALUES (N'Mùa giải 2021', 2021, 1)
GO

INSERT INTO QuyDinh(IDMG, SLDB, SLVD)
VALUES (1, 16, 30)

 INSERT INTO LoaiCauThu(TenLCT, IDMG, SLTD)
  VALUES(N'Cầu thủ trong nước', 1, 45),
		(N'Cầu thủ nước ngoài', 1, 3)


INSERT INTO LoaiBanThang(TenLBT)
VALUES (N'Đánh đầu'),(N'Đá phạt')


ALTER TABLE QUYDINH
ADD TGGBTD varchar(10)

Update QUYDINH
Set TGGBTD = 100
Where IDMG=1 


Update CauThu
Set TONGBANTHANG=0
go

Update QuyDinh
Set QuyDinh.TGGBTD = '90:00'

-- QuyDinhDiemSo 

insert into QuyDinhDiemSo(THANG, HOA, THUA, IDMG) 
values (3, 1, 0, 1)

 -- QuyDinhXepHang Default

insert into QuyDinhXepHang(Ten, ThuTuUuTien, IDMG)
values (N'Điểm', 1, 1)

insert into QuyDinhXepHang(Ten, ThuTuUuTien, IDMG)
values (N'Hiệu số bàn thắng', 2, 1)

insert into QuyDinhXepHang(Ten, ThuTuUuTien, IDMG)
values (N'Tổng số bàn thắng', 3, 1)

insert into QuyDinhXepHang(Ten, ThuTuUuTien, IDMG)
values (N'Tổng số trận thắng', 4, 1)

insert into QuyDinhXepHang(Ten, ThuTuUuTien, IDMG)
values (N'Hiệu số đối đầu ', 5, 1)